include $(THEOS)/makefiles/common.mk

export ARCHS = arm64

TOOL_NAME = zrc-server
zrc-server_FILES = main.mm
zrc-server_LDFLAGS = /Users/zenith/Developer/zrc-server/.golib/libgolang.a

include $(THEOS_MAKE_PATH)/tool.mk

